# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  # An example config option to customise the log level of the workload
  controller-url:
    description: URL of juju controller
    default: ""
    type: string
  juju-user:
    description: Juju username
    default: ""
    type: string
  juju-password:
    description: Password for juju user
    default: ""
    type: string
  scrape-port:
    description: Port to which prometheus exporter is bound.
    default: 5000
    type: int
  scrape-interval:
    description: How often should exporter update its data. (In minutes)
    default: 15
    type: int
  scrape-timeout:
    description: |
      How long should Prometheus wait for response to scrape request before timing out (In seconds)
    default: 30
    type: int